name: Build CMake CI

on:
  push:
    branches-ignore:
      - main
      - python

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.*'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        modules: 'qtshadertools'

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Download bspsrc
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/ata4/bspsrc/releases/latest/download/bspsrc-jar-only.zip" -OutFile "bspsrc.zip"
        Expand-Archive -Path bspsrc.zip -DestinationPath bspsrc
    
    - name: Download vpkeditcli
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/craftablescience/VPKEdit/releases/latest/download/VPKEdit-Windows-Standalone-Compatibility-msvc-Release.zip" -OutFile "vpkedit.zip"
        Expand-Archive -Path vpkedit.zip -DestinationPath vpkedit
        Copy-Item vpkedit\vpkeditcli.exe bin\

    - name: Prepare Artifacts
      shell: pwsh
      run: |
        mkdir release
        Copy-Item build\Release\cs2importer.exe release\
        windeployqt --qmldir src/qml release\cs2importer.exe

        Remove-Item -Path release\translations -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path release\iconengines -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path release\imageformats -Recurse -Force -ErrorAction SilentlyContinue

        Copy-Item -Path bin -Destination release\bin -Recurse
        Copy-Item bspsrc\bspsrc.jar release\bin\
        cd release
        7z a cs2importer.zip *

    - name: Get commit SHA
      id: vars
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CS2-Importer-Dev-${{ steps.vars.outputs.sha_short }}
        path: release/cs2importer.zip
