name: Build CMake CI

on:
  push:
    branches-ignore:
      - main
      - cmake-qt
      - python

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      
    - name: Configure CMake
      run: cmake -B build -S .      
      
    - name: Restore NuGet Packages
      run: nuget restore build/cs2importer.slnx
      
    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Download bspsrc
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/ata4/bspsrc/releases/latest/download/bspsrc-jar-only.zip" -OutFile "bspsrc.zip"
        Expand-Archive -Path bspsrc.zip -DestinationPath bspsrc

    - name: Prepare Artifacts
      shell: pwsh
      run: |
        mkdir release
        Copy-Item build\Release\cs2importer.exe release\
        Copy-Item bspsrc\bspsrc.jar release\

        Copy-Item -Path bin -Destination release\bin -Recurse
        cd release
        7z a cs2importer.zip *

    - name: Get commit SHA
      id: vars
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CS2-Importer-Dev-${{ steps.vars.outputs.sha_short }}
        path: release/cs2importer.zip
