name: Build CMake Release

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.*'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        modules: 'qtshadertools'

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Download bspsrc
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/ata4/bspsrc/releases/latest/download/bspsrc-jar-only.zip" -OutFile "bspsrc.zip"
        Expand-Archive -Path bspsrc.zip -DestinationPath bspsrc
        # It will be placed next to the built executable later

    - name: Prepare Release Artifacts
      shell: pwsh
      run: |
        mkdir release
        # The built executable is usually in build\Release\ on Windows MSVC
        Copy-Item build\Release\cs2importer.exe release\
        Copy-Item bspsrc\bspsrc.jar release\
        # Deploy Qt dependencies next to the executable
        windeployqt --qmldir src/qml release\cs2importer.exe

        # Remove unused Qt folders
        Remove-Item -Path release\translations -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path release\iconengines -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path release\imageformats -Recurse -Force -ErrorAction SilentlyContinue

        Copy-Item -Path bin -Destination release\bin -Recurse
        cd release
        7z a cs2importer.zip *

    - name: Get commit SHA
      id: vars
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: release-${{ steps.vars.outputs.sha_short }}
        name: CS2 Importer Dev ${{ steps.vars.outputs.sha_short }}
        files: release/cs2importer.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
